{
  {
    title: "Born a Crime",
    author: "Trevor Noah",
    publisher: "Spiegel & Grau",
    year: "2016",
    cover_url: "https://bookr-site.netlify.com/imgs/books/born-a-crime.jpg",
    short_description: "Trevor Noah’s unlikely path from apartheid South Africa to the desk of The Daily Show began with a criminal act: his birth.",
    full_description: "Trevor Noah’s unlikely path from apartheid South Africa to the desk of The Daily Show began with a criminal act: his birth. Trevor was born to a white Swiss father and a black Xhosa mother at a time when such a union was punishable by five years in prison. Living proof of his parents’ indiscretion, Trevor was kept mostly indoors for the earliest years of his life, bound by the extreme and often absurd measures his mother took to hide him from a government that could, at any moment, steal him away. Finally liberated by the end of South Africa’s tyrannical white rule, Trevor and his mother set forth on a grand adventure, living openly and freely and embracing the opportunities won by a centuries-long struggle.",
  },
  {
    title: "Hitchhiker's Guide",
    author: "Douglas Adams, Eoin Colfer",
    publisher: "Pan Books",
    year: "1978",
    cover_url: "https://bookr-site.netlify.com/imgs/books/hitchhikers-guide.jpg",
    short_description: "The Hitchhiker's Guide to the Galaxy is the first of five books in the Galaxy comedy science fiction.",
    full_description: "The Hitchhiker's Guide to the Galaxy is the first of five books in the Hitchhiker's Guide to the Galaxy comedy science fiction trilogy by Douglas Adams. The novel is an adaptation of the first four parts of Adams' radio series of the same name. The novel was first published in London on 12 October 1979.",
  },
  {
    title: "The Catcher in the Rye",
    author: "J. D. Salinger",
    publisher: "Little, Brown and Company",
    year: "1951",
    cover_url: "https://bookr-site.netlify.com/imgs/books/the-catcher-in-the-rye.jpg",
    short_description: "The Catcher in the Rye is a story partially published in serial form in 1945.",
    full_description: "The Catcher in the Rye is a story by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951. A classic novel originally published for adults, it has since become popular among adolescent readers for its themes of angst and alienation.",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publisher: "Thomas Egerton",
    year: "1813",
    cover_url: "https://bookr-site.netlify.com/imgs/books/pride-and-prejudice.jpg",
    short_description: "Pride and Prejudice is an 1813 romantic novel by Jane Austen. ",
    full_description: "Pride and Prejudice is an 1813 romantic novel by Jane Austen. It charts the emotional development of the protagonist Elizabeth Bennet, who learns the error of making hasty judgments and comes to appreciate the difference between the superficial and the essential.",
  },
  {
    title: "The Lion and the Mouse",
    author: "Aesop",
    publisher: "Aesop",
    year: "2009",
    cover_url: "https://bookr-site.netlify.com/imgs/books/the-lion-and-the-mouse.jpg",
    short_description: "The Lion and the Mouse is one of Aesop's Fables, numbered 150 in the Perry Index.",
    full_description: "The Lion and the Mouse is one of Aesop's Fables, numbered 150 in the Perry Index. There are also Eastern variants of the story, all of which demonstrate mutual dependence regardless of size or status. In the Renaissance the fable was provided with a sequel condemning social ambition.",
  },
  {
    title: "Aesop's Fables",
    author: "Aesop",
    publisher: "Aesop",
    year: "1983",
    cover_url: "https://bookr-site.netlify.com/imgs/books/aesop-fables.jpg",
    short_description: "Aesop's Fables, or the Aesopica, is a collection of fables credited to Aesop.",
    full_description: "Aesop's Fables, or the Aesopica, is a collection of fables credited to Aesop, a slave and storyteller believed to have lived in ancient Greece between 620 and 564 BCE.",
  },
  {
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    publisher: "O'Reilly Media",
    year: "2014",
    cover_url: "https://bookr-site.netlify.com/imgs/books/you-dont-know-js.jpg",
    short_description: "No matter how much experience you have with JavaScript, odds are you don't fully understand the language.",
    full_description: "No matter how much experience you have with JavaScript, odds are you don't fully understand the language. This concise yet in-depth guide takes you inside scope and closures, two core concepts you need to know to become a more efficient and effective JavaScript programmer. ",
  },
  {
    title: "How To Win Friends And Influence People",
    author: "Dale Carnegie",
    publisher: "Pocket Books",
    year: "1936",
    cover_url: "https://bookr-site.netlify.com/imgs/books/how-to-win-friends-and-influence-people.jpg",
    short_description: "How to Win Friends and Influence People is a self-help book written by Dale Carnegie, published in 1936.",
    full_description: "How to Win Friends and Influence People is a self-help book written by Dale Carnegie, published in 1936. Over 15 million copies have been sold worldwide, making it one of the best-selling books of all time. In 2011, it was number 19 on Time Magazine's list of the 100 most influential books.",
  },
  {
    title: "Introduction to Algorithms",
    author: "Charles E. Leiserson, Clifford Stein, Ronald Rivest, and Thomas H. Cormen",
    publisher: "The MIT Press",
    year: "2009",
    cover_url: "https://bookr-site.netlify.com/imgs/books/introduction-to-algorithms.jpg",
    short_description: "Introduction to Algorithms is a book by Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, and Clifford Stein.",
    full_description: "In the preface, the authors write about how the book was written to be comprehensive and useful in both teaching and professional environments. Each chapter focuses on an algorithm, and discusses its design techniques and areas of application. Instead of using a specific programming language, the algorithms are written in Pseudocode. The descriptions focus on the aspects of the algorithm itself, its mathematical properties, and emphasize efficiency.",
  },
  {
    title: "Grokking Algorithms: An Illustrated Guide for Programmers and Other Curious People",
    author: "Aditya Y. Bhargava",
    publisher: "Manning Publications",
    year: "2016",
    cover_url:"https://bookr-site.netlify.com/imgs/books/grokking-algorithms.jpg",
    short_description: "Summary Grokking Algorithms is a fully illustrated, friendly guide.",
    full_description: "Summary Grokking Algorithms is a fully illustrated, friendly guide that teaches you how to apply common algorithms to the practical problems you face every day as a programmer.",
  },
  {
    title: "Superintelligence: Paths, Dangers, Strategies",
    author: "Nick Bostrom",
    publisher: "Audible Studios on Brilliance Audio",
    year: "2014",
    cover_url:"https://bookr-site.netlify.com/imgs/books/superintelligence-paths-dangers-strategies.jpg",
    short_description: "Superintelligence: Paths, Dangers, Strategies is a 2014 book by the Swedish philosopher Nick Bostrom.",
    full_description: "Superintelligence: Paths, Dangers, Strategies is a 2014 book by the Swedish philosopher Nick Bostrom from the University of Oxford. It argues that if machine brains surpass human brains in general intelligence, then this new superintelligence could replace humans as the dominant lifeform on Earth.",
  },
  {
    title: "How to Create a Mind",
    author: "Ray Kurzweil",
    publisher: "Brilliance Audio",
    year: "2012",
    cover_url:"https://bookr-site.netlify.com/imgs/books/how-to-create-a-mind.jpg",
    short_description: "How to Create a Mind: The Secret of Human Thought Revealed is a non-fiction book about brain.",
    full_description: "How to Create a Mind: The Secret of Human Thought Revealed is a non-fiction book about brains, both human and artificial, by the inventor and futurist Ray Kurzweil. First published in hardcover on November 13, 2012 by Viking Press it became a New York Times Best Seller.",
  },
  {
    title: "Introduction to Korean History and Culture",
    author: "Andrew C. Nahm",
    publisher: "Hollym International Corporation ",
    year: "2010",
    cover_url:"https://bookr-site.netlify.com/imgs/books/introduction-to-korean-history-and-culture.jpg",
    short_description: "Simple, brief, yet comprehensive and interpretive history of Korea for the general reader.",
    full_description: "The purpose of this book is to present the history and culture of Korea to meet the needs of the general reader. While providing essential historical and cultural background of the Korean people, emphasis is given to the process of transformation of the ancient Korean society into an aristocratic/feudalistic state first, and then into a modern nation. ",
  },
  {
    title: "Go Tell it on the Mountain",
    author: "James Baldwin",
    publisher: "Vintage",
    year: "1924",
    cover_url:"https://bookr-site.netlify.com/imgs/books/go-tell-it-on-the-mountain.jpg",
    short_description: "On The Mountain, first published in 1953, is Baldwin's first major work, a novel that has established itself as an American classic.",
    full_description: "On The Mountain, first published in 1953, is Baldwin's first major work, a novel that has established itself as an American classic. With lyrical precision, psychological directness, resonating symbolic power, and a rage that is at once unrelenting and compassionate, Baldwin chronicles a fourteen-year-old boy's discovery of the terms of his identity as the stepson of the minister of a storefront Pentecostal church in Harlem one Saturday in March of 1935.",
  },
  {
    title: "The Unbearable Lightness of Being",
    author: "Milan Kundera",
    publisher: "Harper Perennial Modern Classics",
    year: "2009",
    cover_url:"https://bookr-site.netlify.com/imgs/books/the-unbearable-lightness-of-being.jpg",
    short_description: "Milan Kundera tells the story of a young woman in love with a man torn between his love for her.",
    full_description: "In The Unbearable Lightness of Being, Milan Kundera tells the story of a young woman in love with a man torn between his love for her and his incorrigible womanizing and one of his mistresses and her humbly faithful lover. This magnificent novel juxtaposes geographically distant places; brilliant and playful reflections; and a variety of styles to take its place as perhaps the major achievement of one of the world’s truly great writers.",
  },
}